/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Network {
  Bitcoin = 'Bitcoin',
  Regtest = 'Regtest',
  Signet = 'Signet',
  Testnet = 'Testnet',
}
export const enum LogLevel {
  Gossip = 'Gossip',
  Trace = 'Trace',
  Debug = 'Debug',
  Warn = 'Warn',
  Info = 'Info',
  Error = 'Error',
}
export interface PeerDetails {
  nodeId: string
  address: string
  isPersisted: boolean
  isConnected: boolean
}
export interface ChannelId {
  channelIdHex: string
}
export interface OutPoint {
  txid: string
  vout: number
}
export interface UserChannelId {
  userChannelIdHex: string
}
export interface ChannelDetails {
  channelId: ChannelId
  counterpartyNodeId: string
  fundingTxo?: OutPoint
  channelValueSats: number
  unspendablePunishmentReserve?: number
  userChannelId: UserChannelId
  feerateSatPer1000Weight: number
  balanceMsat: number
  outboundCapacityMsat: number
  inboundCapacityMsat: number
  confirmationsRequired?: number
  confirmations?: number
  isOutbound: boolean
  isChannelReady: boolean
  isUsable: boolean
  isPublic: boolean
  cltvExpiryDelta?: number
}
export interface PaymentPreimage {
  field0: Array<number>
}
export interface PaymentSecret {
  field0: Array<number>
}
export interface PaymentDetails {
  hash: PaymentHash
  preimage?: PaymentPreimage
  secret?: PaymentSecret
  amountMsat?: number
  direction: PaymentDirection
  status: PaymentStatus
}
export const enum PaymentStatus {
  Pending = 'Pending',
  Succeeded = 'Succeeded',
  Failed = 'Failed',
}
export const enum PaymentDirection {
  Inbound = 'Inbound',
  Outbound = 'Outbound',
}
export interface PaymentHash {
  field0: Array<number>
}
export interface Address {
  addressHex: string
}
export interface Txid {
  feild0: string
}
export class ChannelConfig {
  forwardingFeeProportionalMillionths: number
  forwardingFeeBaseMsat: number
  cltvExpiryDelta: number
  maxDustHtlcExposureMsat: number
  forceCloseAvoidanceMaxFeeSatoshis: number
  constructor(
    forwardingFeeProportionalMillionths: number,
    forwardingFeeBaseMsat: number,
    cltvExpiryDelta: number,
    maxDustHtlcExposureMsat: number,
    forceCloseAvoidanceMaxFeeSatoshis: number,
  )
}
export class NetAddress {
  constructor(ipv4: string, port: number)
}
export class PublicKey {
  constructor(nodeId: string)
}
export class Config {
  constructor(
    storageDirPath: string,
    network: Network,
    listeningAddress: NetAddress,
    defaultCltvExpiryDelta: number,
    onchainWalletSyncIntervalSecs: number,
    walletSyncIntervalSecs: number,
    feeRateCacheUpdateIntervalSecs: number,
    logLevel: LogLevel,
  )
}
export class Builder {
  constructor()
  static fromConfig(config: Config): Builder
  setEntropySeedPath(seedPath: string): boolean
  setEntropySeedBytes(seedBytes: Array<number>): boolean
  setEntropyBip39Mnemonic(mnemonic: string, passphrase?: string | undefined | null): boolean
  setEsploraServer(url: string): boolean
  setGossipSourceP2P(): boolean
  setGossipSourceRgs(rgsServerUrl: string): boolean
  setStorageDirPath(storageDirPath: string): boolean
  setNetwork(network: Network): boolean
  setListeningAddress(listeningAddress: NetAddress): boolean
  setLogLevel(level: LogLevel): boolean
  build(): Node
}
export class Node {
  start(): boolean
  stop(): boolean
  syncWallets(): boolean
  nodeId(): string
  listeningAddress(): string | null
  newOnchainAddress(): Address
  sendToOnchainAddress(address: Address, amountMsat: number): Txid
  sendAllToOnchainAddress(address: Address): Txid
  spendableOnchainBalanceSats(): number
  totalOnchainBalanceSats(): number
  connect(nodeId: PublicKey, address: NetAddress, persist: boolean): boolean
  disconnect(counterpartyNodeId: PublicKey): boolean
  connectOpenChannel(
    nodeId: PublicKey,
    address: NetAddress,
    channelAmountSats: number,
    pushToCounterpartyMsat: number | undefined | null,
    channelConfig: ChannelConfig | undefined | null,
    announceChannel: boolean,
  ): boolean
  closeChannel(channelId: ChannelId, counterpartyNodeId: PublicKey): boolean
  receivePayment(amountMsat: number, description: string, expirySecs: number): string
  receiveVariableAmountPayment(description: string, expirySecs: number): string
  sendPayment(invoice: string): PaymentHash
  sendPaymentUsingAmount(invoice: string, amountMsat: number): PaymentHash
  sendSpontaneousPayment(amountMsat: number, nodeId: PublicKey): PaymentHash
  listPayments(): Array<PaymentDetails>
  listPeers(): Array<PeerDetails>
  listChannels(): Array<ChannelDetails>
  payment(paymentHash: PaymentHash): PaymentDetails
  removePayment(paymentHash: PaymentHash): boolean
  signMessage(msg: Array<number>): string
  verifySignature(msg: Array<number>, sig: string, pkey: PublicKey): boolean
  updateChannelConfig(channelId: ChannelId, counterpartyNodeId: PublicKey, channelConfig: ChannelConfig): boolean
}
